/home/smokey/logs/gigahorse-c7-live.log {
    daily
    rotate 14
    size 50M
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
/home/smokey/logs/gigahorse-c7-*.log {
    weekly
    rotate 8
    size 50M
    compress
    delaycompress
    missingok
    notifempty
}

